#!/bin/bash

cd "$(dirname "$0")"

# Build the site
echo "Building site ..."
bundle exec middleman build

# Sync with s3
# www.learningspaces.io.s3-website.eu-central-1.amazonaws.com
echo "Deploying to s3 ..."
aws s3 sync build/ s3://www.learningspaces.io/ --region=eu-central-1 --acl=public-read --delete --cache-control="max-age=1576800000" --exclude "*.html"
aws s3 sync build/ s3://www.learningspaces.io/ --region=eu-central-1 --acl=public-read --delete --cache-control="max-age=0, no-cache" --exclude "*" --include "*.html"
